backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "reviews"
    label: "Book Reviews"
    folder: "_reviews"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Book Title", name: "title", widget: "string"}
      - {label: "Author", name: "author", widget: "string"}
      - {label: "Genre", name: "genre", widget: "string"}
      - {label: "Rating (e.g. 9/10)", name: "rating", widget: "string"}
      - {label: "Your Thoughts", name: "body", widget: "text"}
